spring:
  datasource:
    username: root
    password: safedog@yz2020
    url: jdbc:mysql://localhost:3306/colornote?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapper/**/*.xml
logging:
  root:
    level: debug